### ISSUE TITLE
Update README

### ISSUE THREAD

**Issue by LuongQuyTan1999** [hunguet231/web1#3]
README của bạn hiện tại mình thấy chưa ok lắm(trong thực tế không ai viết README như thế cả). Bạn có thể tham khảo các link sau và viết lại README :
1. https://github.com/nhim175/shave-it 
2. https://github.com/nhim175/coders-tokyo-cli
3. https://github.com/nhim175/coders-tokyo-web

Hướng dẫn viết README chuẩn:
- https://www.makeareadme.com/

**Comment by hunguet231** [comment]
Vâng ạ, em viết lại rồi ạ, anh xem được chưa ạ 😅
